### ISSUE TITLE
spellchecker marks every accented words as wrong (in Spanish)

### ISSUE THREAD

**Issue by aloctavodia** [Calysto/notebook-extensions#1]
I have installed the last version of the callico-spell-checker extension by doing `sudo jupyter nbextension install https://bitbucket.org/ipre/calico/downloads/calico-spell-check-1.0.zip`

followed by `jupyter nbextension enable calico-spell-check`

I added an Spanish dictionary by modifying the file `/usr/local/share/jupyter/nbextensions/calico-spell-check.js` then I create the `/usr/local/share/jupyter/nbextensions/typo/dictionaries/es_AR` folder and I copy there  the files `es_AR.aff` and `es_AR.dir` I take those files from my system (Ubuntu 15.04).  The .dir file has the words correctly accented. 

I am using Jupyter 4.0. Using Ipython 3 and (probably an older version of the spell checker) I had no problem.

Let me know if you need any other information.

**Comment by dsblank** [comment]
I can't replicate your error. In fact it appears to work fine:

![screenshot from 2015-11-15 08 09 57](https://cloud.githubusercontent.com/assets/168568/11168865/48d8d940-8b70-11e5-8766-b1eace8c3505.png)

**Comment by aloctavodia** [comment]
Thanks for taking the time to look at this. 
I also tried changing the encoding from ISO-8859-15 to UTF-8, with no-luck. Any other suggestion? Where did you get the dictionary?

**Comment by dsblank** [comment]
I think this is generally what I did:

```
sudo jupyter nbextension install https://bitbucket.org/ipre/calico/downloads/calico-spell-check-1.0.zip
jupyter nbextension enable calico-spell-check
sudo apt-get install myspell-es
sudo mkdir -p /usr/local/share/jupyter/nbextensions/typo/dictionaries/es_AR
sudo cp /usr/share/hunspell/es_AR.* /usr/local/share/jupyter/nbextensions/typo/dictionaries/es_AR/
## edit /usr/local/share/jupyter/nbextensions/calico-spell-check.js
```

But I may also have a version in /home/dblank/.ipython/nbextensions/... I haven't ruled out that it may be looking there, too.

**Comment by aloctavodia** [comment]
Exactly the same steps, here.

**Comment by dsblank** [comment]
I deleted my ~/.ipython/nbextensions/\* files, and it still works. 
You are clicking the spell check button to turn it on? 
Spanish words with no accent are correctly recognized, but words with accents are not? 
What browser are you using?
No errors showing in the Javascript console?

**Comment by aloctavodia** [comment]
Yes, i'm clicking it to turn it on

I am using firefox, everytime I click on the spell check button I get the message
`accessing `MarkdownCell` is deprecated. Use `require("notebook/js/textcell").MarkdownCell`

Spanish word with no accents are correctly recognize, words with accents are not. I just realize that there are at least one exception. Words that end with the suffix "ción", like asignación, and programación, are recognized as correct words. Words like función are not correctly recognized, programa and programación  are both Spanish words (the same as asigna and asignación), but "func" is not an Spanish word. 

I hope this give you a hint of what is going on.

**Comment by dsblank** [comment]
The word función works for me, both in Firefox and Chrome:

![screenshot from 2015-11-16 08 41 25](https://cloud.githubusercontent.com/assets/168568/11183169/49f76aac-8c3e-11e5-9a8b-80426972afcc.png)

I'm afraid that there is nothing I can do to solve this as I can't replicate it.

**Comment by aloctavodia** [comment]
OK, Thank you!

**Comment by dsblank** [comment]
Closing, as can't replicate. If someone can replicate, and has an idea on what is different, please re-open. Thanks!

**Comment by ochoadavid** [comment]
Hi! I was having exactly the same issue and I think I've found the solution (workaround): my aff and dic files were not utf-8 encoded. So I changed the encoding and the first line of the aff file from: **SET ISO8859-1**
to **SET UTF-8** and now is working as expected.

(Maybe some UTF-8 files can be directly downloaded from the internet).

Hope it helps.
