### ISSUE TITLE
nbextension enabled and validated ok, and buttons show up in the notebook but NOT working

### ISSUE THREAD

**Issue by wsun18** [Calysto/notebook-extensions#11]
Hi 

I am most concerned to numbering sections in the notebook and generating table of content (I think this is supposed to be done by document-tool). Here is what I got after typing 'jupyter nbextension list': 

(py27) C:\code\ipython_notebook>jupyter nbextension list
Known nbextensions:
  config dir: C:\Users\f401569\.jupyter\nbconfig
    notebook section
      calysto/document-tools/main enabled
      - Validating: ok
      calysto/cell-tools/main enabled
      - Validating: ok

I am using jupyter_client 5.0, jupyter_core 4.3, and ipykernel 4.6, ipython 5.3. Could you advise what could be wrong? 

Thanks a lot!

**Comment by dsblank** [comment]
Thanks for reporting! Should be fixed in 0c8c073b4fac6860ac6ed4a81967ba1e162decfd

Please re-download, and re-install

**Comment by wsun18** [comment]
It works perfectly now. Thank you, Man!
