### ISSUE TITLE
How to disable any one of the extension feature?

### ISSUE THREAD

**Issue by shivendra90** [Calysto/notebook-extensions#18]
For now, the most important extension is the spell-checker. I really do not require the publishing and annotate tools. So how do I remove them?

**Comment by dsblank** [comment]
You have full control over install, removing, and enabling these.

For example, you can install just the spelling checker with:

```
jupyter nbextension install calysto/spell-check --user
```

Then it is known as "spell-check" rather than "calysto/spell-check". You can use any of the standard "jupyer nbextension" commands.

**Comment by shivendra90** [comment]
Thanks.

The line `jupyter nbextension disable calysto/publish/main` worked.

Closing.
