### ISSUE TITLE
Text case mismatch in citation links

### ISSUE THREAD

**Issue by cl3wis** [Calysto/notebook-extensions#19]
For instance, if we have some entry named `Surname` in the bibtex, the generated inline link for `### [3rd edition](#cite-Surname)` in the main body is (indented for clarity)
```html
<h3 id="3rd-edition">
    <a href="#cite-Surname">3rd edition</a><a class="anchor-link" href="#3rd-edition">¶</a>
</h3>
```
and the generated html in the References section is (indented for clarity)
```html
<p>
    <a name="cite-surname">
        <sup>[^](#ref-9) </sup>
        Surname, blah blah
    </a>
    <a href="https://website.com/foo/">
        URL
    </a>
</p>
```
So the href in the main text uses the original case, whereas the name in the references section uses the lowercase.

**Comment by cl3wis** [comment]
The code I need to look at for fixing this seems to coincide with #14, so I can work on them both.

**Comment by dsblank** [comment]
Thanks for looking into this!

**Comment by cl3wis** [comment]
No problem! Glad to help. #20

**Comment by marscher** [comment]
this can be closed

**Comment by dsblank** [comment]
Thanks for the note!
