### ISSUE TITLE
calico-document-tools not working in jupyter notebook 4.0

### ISSUE THREAD

**Issue by tuanavu** [Calysto/notebook-extensions#2]

**Comment by dsblank** [comment]
Can you provide some details of how you are installing and why you don't think it is working?

**Comment by tuanavu** [comment]
Sure, I am using a windows 7 - 64 bit, and I have installed Anaconda. After updating ipython notebook to jupyter notebook 4.0

I enable the extension under:

```
~\.jupyter\nbconfig\notebook.json
```

This is the notebook.json file

```
{
  "load_extensions": {
    "livereveal/main": true, 
    "usability/toc/main": true, 
    "usability/codefolding/main": true, 
    "calico-cell-tools": true, 
    "config/config_menu/main": true, 
    "usability/dragdrop/main": true, 
    "calico-document-tools": true, 
    "usability/search-replace/main": true, 
    "calico-spell-check": true, 
    "publishing/printview/main": true, 
    "IPython-notebook-extensions-master/usability/dragdrop/main": true
  }, 
  "nbext_hide_incompat": true
}
```

The jupyter notebook now has all the buttons, and they are all works fine, except the calico-document-tools buttons. Clicking on those buttons, nothing happens.

**Comment by dsblank** [comment]
Do you have any errors showing in the JavaScript Console? What browser are you using? calico-cell-tools and spell-check are working, but not document-tools?

**Comment by tuanavu** [comment]
1) Do you have any errors showing in the JavaScript Console?
With this one, I have the error:

```
%%javascript
IPython.load_extensions('calico-spell-check', 'calico-document-tools', 'calico-cell-tools');
```

```
Javascript error adding output!
TypeError: IPython.load_extensions is not a function
See your browser Javascript console for more details.
```
- Then I am using this command because it is now Jupyter notebook, these commands work fine:

```
!jupyter nbextension install https://bitbucket.org/ipre/calico/downloads/calico-document-tools-1.0.zip
!jupyter nbextension enable calico-document-tools
```

2) What browser are you using?
- Google Chrome

3) calico-cell-tools and spell-check are working, but not document-tools?
- yes

**Comment by vascotenner** [comment]
To show all javascript errors in chrome: right-click on page->inspect element, then choose for console.

**Comment by dsblank** [comment]
Updated install instructions. Should be up to date with modern Jupyter.
