### ISSUE TITLE
Nothing changes after following installation instructions.

### ISSUE THREAD

**Issue by mike-matera** [Calysto/notebook-extensions#21]
Hi, 

Sorry for the very general report. I followed the installation instructions in the readme and there. Everything looks good:

```
$ jupyter nbextension list
Known nbextensions:
  config dir: /home/ec2-user/.jupyter/nbconfig
    notebook section
      calysto/document-tools/main  enabled 
      - Validating: OK
      calysto/cell-tools/main  enabled 
      - Validating: OK
      calysto/spell-check/main  enabled 
      - Validating: OK
      calysto/publish/main  enabled 
      - Validating: OK
      calysto/submit/main  enabled 
      - Validating: OK
      calysto/annotate/main  enabled 
      - Validating: OK
```
But, I don't see any buttons and spell check isn't working. Am I missing something? 

```
$ jupyter --version 
4.4.0
```

**Comment by dsblank** [comment]
How did you install?

**Comment by dsblank** [comment]
Oh, I see: install looks good. Did you restart the notebook?

**Comment by mike-matera** [comment]
Yes. I sure did!

**Comment by dsblank** [comment]
Any errors showing in the javascript console in your browser?

**Comment by dsblank** [comment]
(Just merged an old fix waiting; you may want to re-get/re-install/re-test).

**Comment by mike-matera** [comment]
I hadn't thought to look there. Yes! There is an error that looks relevant: 

I got a 404 while loading:
https://49c5f6a9baad450bb45e201c5c937ce7.vfs.cloud9.us-west-2.amazonaws.com:8081/nbextensions/widgets/notebook/js/extension.js?v=20180810173115

**Comment by mike-matera** [comment]
I just blew away my environment and rebuilt it: no change. 

That process does this: 
```
wget https://github.com/Calysto/notebook-extensions/archive/master.zip
```

Is there a version you think would work? I can try it. 

Could it matter that I'm using `pip install --user`?

**Comment by dsblank** [comment]
As long as "jupyter" and "pip" are working with the right python, I can't think of what else might be wrong.

**Comment by hikinthru** [comment]
@mike-matera 

I was having a similar issue, it was because I didn't understand the last line of the calysto installation: 

```
To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point> --user
```

I didn't understand that meant to add `--user` to the end of the command to enable each feature. Did you do this?

Hope this helps,
Sherrie Fuqua (hikinthru)

**Comment by stefanuddenberg** [comment]
I am having the same issue. I get the following error:

```js
require.js?v=6da8be361b9ee26c5e721e76c6d4afce:900 TypeError: Cannot read property 'help' of undefined
    at toolbar.js:101
    at MainToolBar.ToolBar.add_buttons_group (toolbar.js:115)
    at add_toolbar_buttons (main.js?v=20190127153527:234)
    at Object.load_ipython_extension (main.js?v=20190127153527:257)
    at utils.js:39
    at Object.execCb (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1690)
    at Module.check (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:865)
    at Module.<anonymous> (require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1140)
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:131
    at require.js?v=6da8be361b9ee26c5e721e76c6d4afce:1190
```

**Comment by ricoms** [comment]
what is the `<the entry point>` at:

```
To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point> --user
```
