### ISSUE TITLE
NBExtension installs but will not validate

### ISSUE THREAD

**Issue by acrule** [Calysto/notebook-extensions#4]
I ran `$ jupyter nbextension install https://github.com/Calysto/notebook-extensions/archive/master.zip` and was able to install the extension in /usr/local/share/jupyter/nbextensions. 

However, when I attempt to enable the extension, I get:

```
$ jupyter nbextension enable calico-document-tools
Unrecognized JSON config file version, assuming version 1
Enabling notebook extension calico-document-tools...
      - Validating: problems found:
        - require?  X calico-document-tools
```

Any idea what this error message means?

**Comment by dsblank** [comment]
I suspect that we need to put something in the repo to allow it to work that way.

**Comment by acrule** [comment]
I thought I was following the install instructions from readme.md.  Was I doing it incorrectly?

**Comment by lgpage** [comment]
I had to modify my `~/.jupyter/nbconfig/notebook.json` file as follows:

```
{
  "load_extensions": {
    "notebook-extensions-master/calico-spell-check": true,
    "notebook-extensions-master/calico-document-tools": true
  },
...
```

Spell check however does not work, I get the following console output:
- `Warning: accessing `MarkdownCell` is deprecated. Use `require("notebook/js/textcell").MarkdownCell`
- `Error: TypeError: document.dictionary is undefined`

**Comment by dsblank** [comment]
Updated the code, names, and instructions. Let me know if you still have problems.

**Comment by DeepHorizons** [comment]
I'm having a similar problem. I am able to install and validate the tools, but they do not work in the notebook. On the Jupyter console I'm getting a 404 for the typo.js,

```
[W 14:45:08.208 NotebookApp] 404 GET /nbextensions/typo/typo.js?v=20160907144355 (172.17.0.1) 14.50ms referer=http://127.0.0.1:8888/notebooks/Untitled.ipynb
```

And in the developer console in the notebook when I enable spell check and type:

```
accessing `MarkdownCell` is deprecated. Use `require("notebook/js/textcell").MarkdownCell`   main.min.js:21:11
TypeError: document.dictionary is undefined   main.js:47:2
```

I am also seeing some errors when it is loading:

```
Error: Script error for "nbextensions/typo/typo"
http://requirejs.org/docs/errors.html#scripterror

require.js:165:17
```

Also, the spellcheck from https://bitbucket.org/ipre/calico works for me.

**Comment by dsblank** [comment]
How did you install calysto/spell-check? What version of notebook are you using? Did you try restarting your server?

**Comment by DeepHorizons** [comment]
I installed the spell check via

```
cd /tmp
git clone https://github.com/Calysto/notebook-extensions.git
cd notebook-extensions
jupyter nbextension install calysto --user
jupyter nbextension enable calysto/spell-check/main
```

I'm using Jupyter version 4.1.1 and notebook version 4.2.2. I have tried restarting the server with no luck.

**Comment by dsblank** [comment]
What is the output from:

```
jupyter nbextension list
```

**Comment by DeepHorizons** [comment]
The output of `jupyter nbextension list` is:

```
jovyan@67571c5e9eea:/tmp/notebook-extensions$ jupyter nbextension list
Known nbextensions:
  config dir: /home/jovyan/.jupyter/nbconfig
    notebook section
      calysto/spell-check/main  enabled
      - Validating: OK
  config dir: /opt/conda/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled
      - Validating: OK
```

**Comment by dsblank** [comment]
I'm seeing this too, on one installation. On another everything appears ok. Looking into it...

**Comment by DeepHorizons** [comment]
Ok. If you would like my exact environment, I'm running it in a docker image named `ritjupyter/minimal-notebook`

**Comment by CharlesHolbrow** [comment]
I'm having the same issue as @DeepHorizons. Any chance of looking at this more?

**Comment by xiaohk** [comment]
I installed via git. The installation looks fine, but this extension does not work in the notebook.

**Comment by rschroll** [comment]
I seem to be having the same problem as @DeepHorizons.  I managed to solve it by changing line 105 of spell-check/main.js from
```js
       require(["nbextensions/typo/typo"], function () {
```
to
```js
       require(["nbextensions/calysto/spell-check/typo/typo"], function () {
```

I don't know if that's "proper", but it does seem to work.  I can submit a PR with this change if you'd like.

**Comment by dsblank** [comment]
That is probably correct. Please do make a PR and I'll test as well. Thanks!

**Comment by DeepHorizons** [comment]
I can verify that #6 fixes the problem
