### ISSUE TITLE
Is it possible to switch spell checking language?

### ISSUE THREAD

**Issue by quang-ha** [Calysto/notebook-extensions#5]
I know it is quick picky of me but any chance it could be changed to British English?

**Comment by dsblank** [comment]
You can change this yourself:
1. Download a new Hunspell-type dictionary (eg, https://sourceforge.net/projects/wordlist/files/speller/2016.06.26/)
2. Put it in the calysto/spell-check/typo/dictionaries/ folder
3. Edit calysto/spell-check/main.js:

``` javascript
var lang = "en_GB-ise";
```
